<?php
return [
    "login" => "Login",
    "student_id" => "Student ID",
    "password" => "Password",
    "login_button" => "Login",
    "no_account" => "Don't have an account?",
    "register_now" => "Register now",

    "register_title" => "Register Account",
    "full_name" => "Full Name",
    "university_id" => "University ID",
    "email" => "Email",
    "complete_form" => "Complete the Form",
    "complete_form_alert" => "Please click 'Complete the Form' before registering.",
    "college" => "College",
    "select_college" => "Select College",
    "college_computer" => "Computer",
    "college_engineering" => "Engineering",
    "college_science" => "Science",
    "region" => "Region",
    "phone_number" => "Phone Number",
    "level" => "Level",
    "confirm_password" => "Confirm Password",
    "register" => "Register",
    "already_have_account" => "Already have an account?",

    "home_title" => "Housing System - Home Page",
    "navbar_title" => "Housing System",
    "track_requests" => "Track Requests",
    "logout" => "Logout",
    "about_title" => "About the Student Housing System",
    "about_description" => "The housing system offers various services such as room booking, maintenance, and complaints...",
    "header_title" => "Welcome to the University Housing System",
    "header_description" => "We provide the best services for students easily and quickly.",
    "services" => "Services",
    "service1_title" => "Room Booking",
    "service1_desc" => "Book your room easily through our site.",
    "service1_btn" => "Get Started",
    "service2_title" => "Maintenance Request",
    "service2_desc" => "Send maintenance requests quickly and easily.",
    "service2_btn" => "Request Now",
    "service3_title" => "Submit Complaint",
    "service3_desc" => "Submit your complaint and we’ll help you.",
    "service3_btn" => "Submit Complaint",
    "service4_title" => "Contract Renewal / Clearance",
    "service4_desc" => "Submit a contract renewal or clearance request easily.",
    "service4_btn" => "Apply Now",
    "footer_text" => "© 2025 Housing System. All rights reserved."
];
