<?php
return [
    "login" => "تسجيل الدخول",
    "student_id" => "الرقم الجامعي",
    "password" => "كلمة المرور",
    "login_button" => "تسجيل الدخول",
    "no_account" => "ليس لديك حساب؟",
    "register_now" => "سجل الآن",

    "register_title" => "تسجيل حساب جديد",
    "full_name" => "الاسم الكامل",
    "university_id" => "الرقم الجامعي",
    "email" => "البريد الإلكتروني",
    "complete_form" => "أكمل النموذج",
    "complete_form_alert" => "يرجى الضغط على زر 'أكمل النموذج' قبل التسجيل.",
    "college" => "الكلية",
    "select_college" => "اختر الكلية",
    "college_computer" => "كلية الحاسبات",
    "college_engineering" => "كلية الهندسة",
    "college_science" => "كلية العلوم",
    "region" => "المنطقة",
    "phone_number" => "رقم الجوال",
    "level" => "المستوى",
    "confirm_password" => "تأكيد كلمة المرور",
    "register" => "تسجيل",
    "already_have_account" => "هل لديك حساب بالفعل؟",

    "home_title" => "نظام السكن - الصفحة الرئيسية",
    "navbar_title" => "نظام السكن",
    "track_requests" => "متابعة الطلبات",
    "logout" => "تسجيل الخروج",
    "about_title" => "حول نظام سكن الطلاب",
    "about_description" => "نظام السكن يقدم خدمات متعددة للطلاب، منها الحجز، الصيانة، والشكاوى...",
    "header_title" => "مرحبًا بك في نظام السكن الجامعي",
    "header_description" => "نوفر أفضل الخدمات للطلاب بطريقة سهلة وسريعة.",
    "services" => "الخدمات",
    "service1_title" => "حجز غرفة",
    "service1_desc" => "احجز غرفتك بسهولة من خلال موقعنا.",
    "service1_btn" => "ابدأ الآن",
    "service2_title" => "طلب صيانة",
    "service2_desc" => "أرسل طلبات الصيانة بسرعة وسهولة.",
    "service2_btn" => "اطلب الآن",
    "service3_title" => "تقديم شكوى",
    "service3_desc" => "قدّم شكواك وسنقوم بمساعدتك فورًا.",
    "service3_btn" => "قدم شكوى",
    "service4_title" => "تجديد عقد / إخلاء طرف",
    "service4_desc" => "يمكنك تجديد العقد أو تقديم طلب إخلاء طرف بسهولة.",
    "service4_btn" => "قدّم الآن",
    "footer_text" => "© 2025 نظام السكن. جميع الحقوق محفوظة."
];
